stages:
  extract_archive:
    cmd: unzip -q dataset_fixed.zip -d datasets/
    deps:
    - dataset_fixed.zip
    outs:
    - datasets/dataset_fixed/
  split_dataset:
    cmd: python split_dataset.py
    deps:
    - datasets/dataset_fixed/
    - split_dataset.py
    outs:
    - datasets/x_train.pickle
    - datasets/x_test.pickle
    - datasets/y_train.pickle
    - datasets/y_test.pickle
    params:
    - split_dataset.train_size
  train_model:
    cmd: python train_model.py
    deps:
    - datasets/x_test.pickle
    - datasets/x_train.pickle
    - datasets/y_test.pickle
    - datasets/y_train.pickle
    - train_model.py
    outs:
    - models/model.pickle:
        cache: false
    metrics:
    - metrics.json:
        cache: false
